module.exports ={
    colors:{
      col1:'white',
      text1:'red',
      text2:'gray',
      tetx3:'black'
    },
    titles:{
        title1:30,
        btnTxt: 20,
    },
    btn1:{
        width:'80%',
        height:50,
        backgroundColor:'red',
        borderRadius:10,
        alignItems:'center',
        justifyContent:'center',
        elevation:10,
        color:'white',
        marginTop:5,
    },
    hr80:{
        width:'80%',
        borderBottomColor:'lightgray',
        borderBottomWidth:1,
        marginVertical:15,
    }
}